@echo off
echo Committing deployment fix...
git add package.json package-lock.json
git commit -m "Fix: update @google/genai to 1.35.0 to resolve Vercel deploy error"
echo Pushing to GitHub...
git push
echo Done! checking deployment status...
pause
